### ISSUE TITLE
Type Error ical2txt

### ISSUE THREAD

**Issue by ifuchs** [erikcox/ical2csv#12]
I tried ical2txt limiting it to a 14 day period and got:

Processing events : Traceback (most recent call last):
  File "ical2txt.py", line 176, in <module>
    txt_write(filename) # Write the matching events to the textfile. With recurring_ical_events, scoping is already done.
  File "ical2txt.py", line 127, in txt_write
    if event.location != '': values = values + " [" + event.location + "]" # Only include location if there is one
TypeError: can only concatenate str (not "NoneType") to str

WIthout the date limit, I got the same Type Error as with ical2csv.

**Comment by martinm76** [comment]
Hmm. I thought I had handled that. I'll take a look.
