### ISSUE TITLE
ical2txt.py doesn't work without start and end time

### ISSUE THREAD

**Issue by mkoegel** [erikcox/ical2csv#9]
Hi,
thanks for writing this tool.

I get the following error:
```
python3 ical2txt.py export.ics    
Extracting events from file: export.ics 

Traceback (most recent call last):
  File "ical2txt.py", line 156, in <module>
    txt_write(filename)
  File "ical2txt.py", line 96, in txt_write
    if sys.argv[2] != '':
IndexError: list index out of range

```

 It works when I use start and end dates:
`python3 ical2txt.py export.ics 2021-05-01 2021-05-31`

Would also be nice to mention this option in the readme.

Quickfix:
```
    if len(sys.argv) > 3:
        if sys.argv[2] != '':
            istart=parse(sys.argv[2]).timestamp()
        if sys.argv[3] != '':
            istop=parse(sys.argv[3]).timestamp()
```

**Comment by martinm76** [comment]
Thank you for your quickfix. I'll update it on my branch and hope Erik pulls it.

**Comment by martinm76** [comment]
I have updated my branch now with fix for this and a few other edge cases, updated the documentation and implemented recurring events with extra library (I though icalendar expanded these, but it did not).
I'll see if I can send a pull request to Erik.
Currently I have not modified ical2csv. Let me know if you use that.

**Comment by martinm76** [comment]
This should be fixed. There may be a slight issue with having timezones applied. I believe I have a fix locally. Will push it here soon.

**Comment by martinm76** [comment]
Timezone issue should be resolved as well, once/if Erik accepts my pull request ;-)
